### ISSUE TITLE
Will be great if this plugin also adds lines numbers for code

### ISSUE THREAD

**Issue by nodkz** [bnjmnt4n/reveal-code-focus#16]
Will be great if this plugin also has built-in lines numbers support for the code.

For now, I'm doing this via CSS:
```css
code {
	counter-reset: line;
}
code > span {
	counter-increment: line;
}
code > span:before {
	content: counter(line);
	text-align: right;
	color: #555;
	/* border-right: 1px solid #555; */
	width: 40px;
	padding-right: 8px;
	margin-right: 8px;
	display: inline-block;
	-webkit-touch-callout: none;
	-webkit-user-select: none;
	-khtml-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none; 
	user-select: none;
}
```

Thanks for amazing plugin!
